server:
   port: 7003
   
eureka:
   instance:
      hostname: eureka7003.com                     #localhost#eureka服务端实例名称
   client:
      #registerWithEureka: false                  #是否要注册到其他Server上   registerWithEureka等同于register_with_eureka   
      #fetchRegistry: false                        #是否需要拉取服务信息       fetchRegistry等同于 fetch-registry
      register-with-eureka: false                  #false表示不向服务中心注册自己
      fetch-registry: false                        #false表示自己端就是注册中心,我的职责就是维护实例并不需要去检索服务
      service-url:
         #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/               #设置 Eureka Service 交互的地址查询服务和注册服务都需要依赖这个地址         
         defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/           